[package]
name = "common_loading_screen"
version.workspace = true
edition.workspace = true

[dependencies]
bevy.workspace = true
common_assets.workspace = true
common_visuals.workspace = true
rand.workspace = true
strum.workspace = true
