[package]
name = "main_game"
edition.workspace = true
version.workspace = true

[[bin]]
name = "game"
path = "src/main.rs"

[dependencies]
bevy.workspace = true
main_game_lib.workspace = true
scene_apartment.workspace = true
scene_downtown.workspace = true
scene_meditation.workspace = true

[features]
dev = ["scene_meditation/dev", "scene_downtown/dev", "scene_apartment/dev"]
