[package]
name = "main_game"
edition.workspace = true
version.workspace = true
default-run = "game"


[[bin]]
name = "game"
path = "src/main.rs"


[dependencies]
bevy.workspace = true
common_loading_screen.workspace = true
common_store.workspace = true
common_story.workspace = true
main_game_lib.workspace = true
scene_apartment.workspace = true
scene_downtown.workspace = true
scene_meditation.workspace = true


[features]
devtools = [
    "main_game_lib/devtools",
    "scene_meditation/devtools",
    "scene_downtown/devtools",
    "scene_apartment/devtools",
]
