[package]
name = "main_game"
edition.workspace = true
version.workspace = true
default-run = "game"

[[bin]]
name = "game"
path = "src/main.rs"

[dependencies]
bevy.workspace = true
main_game_lib.workspace = true
scene_apartment.workspace = true
scene_downtown.workspace = true
scene_meditation.workspace = true

[build-dependencies]
common_top_down = { workspace = true, features = ["build-script"] }
scene_apartment.workspace = true

[features]
dev = ["scene_meditation/dev", "scene_downtown/dev", "scene_apartment/dev"]
