[package]
name = "main_game"
edition.workspace = true
version.workspace = true

[[bin]]
name = "game"
path = "src/main.rs"

[dependencies]
bevy.workspace = true
main_game_lib.workspace = true
meditation.workspace = true
apartment = { workspace = true, features = ["dev"] }
