[package]
name = "main_game"
edition.workspace = true
version.workspace = true

[[bin]]
name = "game"
path = "src/main.rs"

[dependencies]
apartment.workspace = true
bevy.workspace = true
downtown.workspace = true
main_game_lib.workspace = true
meditation.workspace = true

[features]
dev = ["meditation/dev", "downtown/dev", "apartment/dev"]
