[package]
name = "common_visuals"
version.workspace = true
edition.workspace = true

[dependencies]
bevy.workspace = true
common_ext.workspace = true
lazy_static.workspace = true
rand.workspace = true

[features]
default = ["fps"]

fps = []
