[workspace]

resolver = "2"
members = ["meditation"]

[workspace.dependencies]
bevy = "0.12"
bevy_pixel_camera = "0.12"
rand = "0.8"

# compile deps packages in dev with optimizations
# this makes bevy run fast and bin recompile fast
[profile.dev.package."*"]
opt-level = 3
