/// This is an autogenerated implementation by the map maker tool.
impl main_game_lib::top_down::layout::ZoneTile for crate::MallTileKind {
    #[inline]
    fn zone_group(&self) -> Option<main_game_lib::top_down::layout::ZoneGroup> {
        todo!()
    }
    #[inline]
    fn zone_size(&self) -> Option<usize> {
        todo!()
    }
    type Successors = Self;
    #[inline]
    fn zone_successors(&self) -> Option<&'static [Self::Successors]> {
        todo!()
    }
}
