[package]
name = "meditation"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy.workspace = true
bevy_pixel_camera.workspace = true
rand.workspace = true
image = "0.24"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
crossbeam-channel = "0.5"
