[package]
name = "meditation"
version.workspace = true
edition.workspace = true

[dependencies]
bevy_pixel_camera.workspace = true
bevy-webp-anim = { path = "../bevy-webp-anim" }
bevy.workspace = true
common-physics = { path = "../common/physics" }
common-visuals = { path = "../common/visuals" }
rand.workspace = true
