[package]
name = "meditation"
version.workspace = true
edition.workspace = true

[dependencies]
bevy_pixel_camera.workspace = true
bevy-webp-anim = { path = "../bevy-webp-anim" }
bevy.workspace = true
project-physics = { path = "../project/physics" }
project-visuals = { path = "../project/visuals" }
rand.workspace = true
