/// This is an autogenerated implementation by the map maker tool.
#[rustfmt::skip] impl crate::layout::DevPlaygroundTileKind
{
    fn zone_group_autogen(&self) -> Option<common_top_down::layout::ZoneGroup>
    {
        use common_top_down::layout::ZoneGroup; match self
        { Self::ZoneA => Some(ZoneGroup(0)),
Self::ZoneB => Some(ZoneGroup(0)),
Self::ZoneC => Some(ZoneGroup(1)),
Self::ZoneD => Some(ZoneGroup(0)),
Self::ZoneE => Some(ZoneGroup(0)),
Self::ZoneF => Some(ZoneGroup(0)),
Self::ZoneG => Some(ZoneGroup(0)),
Self::ZoneH => Some(ZoneGroup(1)),
Self::ZoneI => Some(ZoneGroup(0)),
Self::ZoneJ => Some(ZoneGroup(0)),
Self::ZoneK => Some(ZoneGroup(0)),
 #[allow(unreachable_patterns)] _ => None, }
    }
}