# added after talking to Marie for the first time

[root]
who = "Winnie"
en = "So Marie is quite the oddball, huh?"
[[node]]
who = "Bolt"
en = """Lorem ipsum dolor sit amet, consectetur adipiscing elit
sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
pariatur.
"""
[[node]]
who = "Winnie"
en = "Amen"
next = "_end_dialog"
