[root]
who = "Winnie"
en = "Hey"
[[node]]
who = "Bolt"
en = "I don't talk to strangers."
[[node]]
guard = "remove_dialog_from_npc"
# who is implied to be Bolt, and remove this dialog so that it doesn't repeat
params = { file_path = "bolt_is_mean.toml" }
next = "_end_dialog"
