[root]
who = "Winnie"
en = "Let's see, I'm going to ..."
# DO NOT RENAME ANY, elevator cutscene depends on this
next = ["go_to_downtown", "go_to_basement1", "exit_elevator"]

[[node]]
name = "go_to_downtown"
en = "go outside"
next = "_end_dialog"

[[node]]
name = "go_to_basement1"
en = "the basement"
next = "_end_dialog"

[[node]]
name = "exit_elevator"
en = "exit the elevator"
next = "_end_dialog"
