[root]
who = "GingerCat"
en = """*With a substantial effort on her part, the cat's eyes meet yours.
This cat is clearly out of it.*"""
[[node]]
en = "Good Water."
[[node]]
en = "You buy some?"
next = ["taste_test", "yes_water", "no_water"]

[[node]]
name = "yes_water"
who = "Winnie"
en = "Sure, let me have some. How much is it?"
next = "cost"

[[node]]
name = "taste_test"
who = "Winnie"
en = "Isn't this a taste test stand?"
# TODO: here's where we can add a roll
[[node]]
who = "GingerCat"
en = "No, it's a water stand."
next = "cost"

[[node]]
who = "GingerCat"
name = "cost"
en = "A bag of peas, please."
[[node]]
who = "Winnie"
en = "Peas? Do you not accept cash?"
[[node]]
who = "GingerCat"
en = "No peas no cash, please."
[[node]]
who = "Winnie"
en = """What?

Well, anyway, I don't have no peas.
"""
# TODO: We can add a note to the player's quest log here, and if they come with
# peas that can be obtained in the cult's garden, they can go to the next dialog
# with the cat.
[[node]]
who = "GingerCat"
en = "Then no water, please."
next = "get_ignored"

[[node]]
name = "no_water"
who = "Winnie"
en = "I'm good, thanks."
next = "get_ignored"

[[node]]
name = "get_ignored"
who = "GingerCat"
en = "*proceeds to stare past you as if you weren't even there*"
next = ["aggressive_leave", "leave"]

[[node]]
name = "aggressive_leave"
who = "Winnie"
en = "One rude little kitty"
next = "_end_dialog"

[[node]]
name = "leave"
en = "*leave*"
next = "_end_dialog"
