[package]
name = "main_game_lib"
edition.workspace = true
version.workspace = true

[dependencies]
bevy_magic_light_2d.workspace = true
bevy_pixel_camera.workspace = true
bevy_webp_anim.workspace = true
bevy-inspector-egui.workspace = true
bevy.workspace = true
common_action.workspace = true
common_loading_screen.workspace = true
common_store.workspace = true
common_visuals.workspace = true
