[package]
name = "bevy_webp_anim"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12"
image = "0.24"
thiserror = "1.0"
tokio = { version = "1.35", features = ["rt", "sync", "rt-multi-thread"] }

[[example]]
name = "basic"
path = "examples/basic.rs"
