[package]
name = "common_actor"
version.workspace = true
edition.workspace = true

[dependencies]
bevy.workspace = true
leafwing-input-manager.workspace = true
common_layout.workspace = true
common_action.workspace = true
bevy_grid_squared.workspace = true
common_story.workspace = true
