[package]
name = "common_rscn"
edition.workspace = true
version.workspace = true

[dependencies]
bevy.workspace = true
common_ext.workspace = true
common_top_down.workspace = true
common_visuals.workspace = true
logos.workspace = true
serde.workspace = true
thiserror.workspace = true
