[package]
name = "common_story"
version.workspace = true
edition.workspace = true

[dependencies]
bevy-inspector-egui.workspace = true
bevy.workspace = true
common_action.workspace = true
common_assets.workspace = true
common_store.workspace = true
common_story_derive = { path = "derive" }
common_visuals.workspace = true
itertools.workspace = true
strum.workspace = true
