[package]
name = "common-physics"
version.workspace = true
edition.workspace = true

[dependencies]
bevy.workspace = true

[features]
default = ["poissons-eq"]

poissons-eq = []
poissons-eq-visualization = []
