/// This is an autogenerated implementation by the map maker tool.
#[rustfmt::skip] impl crate::layout::ApartmentTileKind
{
    #[inline] fn zone_group_autogen(&self) ->
    Option<common_top_down::layout::ZoneGroup>
    {
        use common_top_down::layout::ZoneGroup; match self
        { Self::HallwayZone => Some(ZoneGroup(0)),
Self::PlayerApartmentZone => Some(ZoneGroup(0)),
Self::BedZone => Some(ZoneGroup(0)),
Self::ElevatorZone => Some(ZoneGroup(0)),
Self::PlayerDoorZone => Some(ZoneGroup(0)),
Self::MeditationZone => Some(ZoneGroup(0)),
Self::TeaZone => Some(ZoneGroup(0)),
 #[allow(unreachable_patterns)] _ => None, }
    }
}
