[package]
name = "apartment"
version.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
bevy_pixel_camera.workspace = true
bevy.workspace = true
main_game_lib.workspace = true

[features]
dev = ["bevy/glam_assert"]
