[package]
name = "bevy-webp-anim"
version.workspace = true
edition.workspace = true

[dependencies]
bevy.workspace = true
image.workspace = true
serde.workspace = true
thiserror.workspace = true
crossbeam-channel.workspace = true
