name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-02-01
          components: rustfmt, clippy
      - name: Format
        run: cargo fmt -- --check
      - name: Check
        run: cargo check
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Test
        run: cargo test
